// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.35.1
// source: api/proto/iam/audit/v1/access_lifecycle.proto

package auditv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Metadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Platform      string                 `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`
	UserAgent     string                 `protobuf:"bytes,3,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	DeviceId      string                 `protobuf:"bytes,4,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Email         string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_api_proto_iam_audit_v1_access_lifecycle_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_iam_audit_v1_access_lifecycle_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_api_proto_iam_audit_v1_access_lifecycle_proto_rawDescGZIP(), []int{0}
}

func (x *Metadata) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *Metadata) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *Metadata) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *Metadata) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *Metadata) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type Actor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Metadata      *Metadata              `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Actor) Reset() {
	*x = Actor{}
	mi := &file_api_proto_iam_audit_v1_access_lifecycle_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Actor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Actor) ProtoMessage() {}

func (x *Actor) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_iam_audit_v1_access_lifecycle_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Actor.ProtoReflect.Descriptor instead.
func (*Actor) Descriptor() ([]byte, []int) {
	return file_api_proto_iam_audit_v1_access_lifecycle_proto_rawDescGZIP(), []int{1}
}

func (x *Actor) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Actor) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type Service struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Owners        []*Actor               `protobuf:"bytes,3,rep,name=owners,proto3" json:"owners,omitempty"`
	Metadata      *Metadata              `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Service) Reset() {
	*x = Service{}
	mi := &file_api_proto_iam_audit_v1_access_lifecycle_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_iam_audit_v1_access_lifecycle_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service.ProtoReflect.Descriptor instead.
func (*Service) Descriptor() ([]byte, []int) {
	return file_api_proto_iam_audit_v1_access_lifecycle_proto_rawDescGZIP(), []int{2}
}

func (x *Service) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Service) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Service) GetOwners() []*Actor {
	if x != nil {
		return x.Owners
	}
	return nil
}

func (x *Service) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type Access struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Service       *Service               `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Since         *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=since,proto3" json:"since,omitempty"`
	Till          *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=till,proto3" json:"till,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Access) Reset() {
	*x = Access{}
	mi := &file_api_proto_iam_audit_v1_access_lifecycle_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Access) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Access) ProtoMessage() {}

func (x *Access) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_iam_audit_v1_access_lifecycle_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Access.ProtoReflect.Descriptor instead.
func (*Access) Descriptor() ([]byte, []int) {
	return file_api_proto_iam_audit_v1_access_lifecycle_proto_rawDescGZIP(), []int{3}
}

func (x *Access) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Access) GetService() *Service {
	if x != nil {
		return x.Service
	}
	return nil
}

func (x *Access) GetSince() *timestamppb.Timestamp {
	if x != nil {
		return x.Since
	}
	return nil
}

func (x *Access) GetTill() *timestamppb.Timestamp {
	if x != nil {
		return x.Till
	}
	return nil
}

type Role struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Accesses      []*Access              `protobuf:"bytes,2,rep,name=accesses,proto3" json:"accesses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Role) Reset() {
	*x = Role{}
	mi := &file_api_proto_iam_audit_v1_access_lifecycle_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Role) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Role) ProtoMessage() {}

func (x *Role) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_iam_audit_v1_access_lifecycle_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Role.ProtoReflect.Descriptor instead.
func (*Role) Descriptor() ([]byte, []int) {
	return file_api_proto_iam_audit_v1_access_lifecycle_proto_rawDescGZIP(), []int{4}
}

func (x *Role) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Role) GetAccesses() []*Access {
	if x != nil {
		return x.Accesses
	}
	return nil
}

type Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Decision      string                 `protobuf:"bytes,1,opt,name=decision,proto3" json:"decision,omitempty"`
	Role          *Role                  `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Comment       string                 `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_api_proto_iam_audit_v1_access_lifecycle_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_iam_audit_v1_access_lifecycle_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_api_proto_iam_audit_v1_access_lifecycle_proto_rawDescGZIP(), []int{5}
}

func (x *Result) GetDecision() string {
	if x != nil {
		return x.Decision
	}
	return ""
}

func (x *Result) GetRole() *Role {
	if x != nil {
		return x.Role
	}
	return nil
}

func (x *Result) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type IAMAuditEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TraceId        string                 `protobuf:"bytes,2,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	OrderId        int64                  `protobuf:"varint,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Timestamp      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Environment    string                 `protobuf:"bytes,5,opt,name=environment,proto3" json:"environment,omitempty"`
	Type           string                 `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	Subject        *Actor                 `protobuf:"bytes,7,opt,name=subject,proto3" json:"subject,omitempty"`
	Services       []*Service             `protobuf:"bytes,8,rep,name=services,proto3" json:"services,omitempty"`
	RequestComment string                 `protobuf:"bytes,9,opt,name=request_comment,json=requestComment,proto3" json:"request_comment,omitempty"`
	Admin          *Actor                 `protobuf:"bytes,10,opt,name=admin,proto3" json:"admin,omitempty"`
	Result         *Result                `protobuf:"bytes,11,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *IAMAuditEvent) Reset() {
	*x = IAMAuditEvent{}
	mi := &file_api_proto_iam_audit_v1_access_lifecycle_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IAMAuditEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IAMAuditEvent) ProtoMessage() {}

func (x *IAMAuditEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_iam_audit_v1_access_lifecycle_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IAMAuditEvent.ProtoReflect.Descriptor instead.
func (*IAMAuditEvent) Descriptor() ([]byte, []int) {
	return file_api_proto_iam_audit_v1_access_lifecycle_proto_rawDescGZIP(), []int{6}
}

func (x *IAMAuditEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *IAMAuditEvent) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *IAMAuditEvent) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *IAMAuditEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *IAMAuditEvent) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *IAMAuditEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *IAMAuditEvent) GetSubject() *Actor {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *IAMAuditEvent) GetServices() []*Service {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *IAMAuditEvent) GetRequestComment() string {
	if x != nil {
		return x.RequestComment
	}
	return ""
}

func (x *IAMAuditEvent) GetAdmin() *Actor {
	if x != nil {
		return x.Admin
	}
	return nil
}

func (x *IAMAuditEvent) GetResult() *Result {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_api_proto_iam_audit_v1_access_lifecycle_proto protoreflect.FileDescriptor

const file_api_proto_iam_audit_v1_access_lifecycle_proto_rawDesc = "" +
	"\n" +
	"-api/proto/iam/audit/v1/access_lifecycle.proto\x12\fiam.audit.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x88\x01\n" +
	"\bMetadata\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x1a\n" +
	"\bplatform\x18\x02 \x01(\tR\bplatform\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x03 \x01(\tR\tuserAgent\x12\x1b\n" +
	"\tdevice_id\x18\x04 \x01(\tR\bdeviceId\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\"K\n" +
	"\x05Actor\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x122\n" +
	"\bmetadata\x18\x02 \x01(\v2\x16.iam.audit.v1.MetadataR\bmetadata\"\x8e\x01\n" +
	"\aService\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12+\n" +
	"\x06owners\x18\x03 \x03(\v2\x13.iam.audit.v1.ActorR\x06owners\x122\n" +
	"\bmetadata\x18\x04 \x01(\v2\x16.iam.audit.v1.MetadataR\bmetadata\"\xab\x01\n" +
	"\x06Access\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12/\n" +
	"\aservice\x18\x02 \x01(\v2\x15.iam.audit.v1.ServiceR\aservice\x120\n" +
	"\x05since\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x05since\x12.\n" +
	"\x04till\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x04till\"H\n" +
	"\x04Role\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x120\n" +
	"\baccesses\x18\x02 \x03(\v2\x14.iam.audit.v1.AccessR\baccesses\"f\n" +
	"\x06Result\x12\x1a\n" +
	"\bdecision\x18\x01 \x01(\tR\bdecision\x12&\n" +
	"\x04role\x18\x02 \x01(\v2\x12.iam.audit.v1.RoleR\x04role\x12\x18\n" +
	"\acomment\x18\x03 \x01(\tR\acomment\"\xa9\x03\n" +
	"\rIAMAuditEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\btrace_id\x18\x02 \x01(\tR\atraceId\x12\x19\n" +
	"\border_id\x18\x03 \x01(\x03R\aorderId\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12 \n" +
	"\venvironment\x18\x05 \x01(\tR\venvironment\x12\x12\n" +
	"\x04type\x18\x06 \x01(\tR\x04type\x12-\n" +
	"\asubject\x18\a \x01(\v2\x13.iam.audit.v1.ActorR\asubject\x121\n" +
	"\bservices\x18\b \x03(\v2\x15.iam.audit.v1.ServiceR\bservices\x12'\n" +
	"\x0frequest_comment\x18\t \x01(\tR\x0erequestComment\x12)\n" +
	"\x05admin\x18\n" +
	" \x01(\v2\x13.iam.audit.v1.ActorR\x05admin\x12,\n" +
	"\x06result\x18\v \x01(\v2\x14.iam.audit.v1.ResultR\x06resultB*Z(iam-audit/api/proto/iam/audit/v1;auditv1b\x06proto3"

var (
	file_api_proto_iam_audit_v1_access_lifecycle_proto_rawDescOnce sync.Once
	file_api_proto_iam_audit_v1_access_lifecycle_proto_rawDescData []byte
)

func file_api_proto_iam_audit_v1_access_lifecycle_proto_rawDescGZIP() []byte {
	file_api_proto_iam_audit_v1_access_lifecycle_proto_rawDescOnce.Do(func() {
		file_api_proto_iam_audit_v1_access_lifecycle_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_iam_audit_v1_access_lifecycle_proto_rawDesc), len(file_api_proto_iam_audit_v1_access_lifecycle_proto_rawDesc)))
	})
	return file_api_proto_iam_audit_v1_access_lifecycle_proto_rawDescData
}

var file_api_proto_iam_audit_v1_access_lifecycle_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_proto_iam_audit_v1_access_lifecycle_proto_goTypes = []any{
	(*Metadata)(nil),              // 0: iam.audit.v1.Metadata
	(*Actor)(nil),                 // 1: iam.audit.v1.Actor
	(*Service)(nil),               // 2: iam.audit.v1.Service
	(*Access)(nil),                // 3: iam.audit.v1.Access
	(*Role)(nil),                  // 4: iam.audit.v1.Role
	(*Result)(nil),                // 5: iam.audit.v1.Result
	(*IAMAuditEvent)(nil),         // 6: iam.audit.v1.IAMAuditEvent
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_api_proto_iam_audit_v1_access_lifecycle_proto_depIdxs = []int32{
	0,  // 0: iam.audit.v1.Actor.metadata:type_name -> iam.audit.v1.Metadata
	1,  // 1: iam.audit.v1.Service.owners:type_name -> iam.audit.v1.Actor
	0,  // 2: iam.audit.v1.Service.metadata:type_name -> iam.audit.v1.Metadata
	2,  // 3: iam.audit.v1.Access.service:type_name -> iam.audit.v1.Service
	7,  // 4: iam.audit.v1.Access.since:type_name -> google.protobuf.Timestamp
	7,  // 5: iam.audit.v1.Access.till:type_name -> google.protobuf.Timestamp
	3,  // 6: iam.audit.v1.Role.accesses:type_name -> iam.audit.v1.Access
	4,  // 7: iam.audit.v1.Result.role:type_name -> iam.audit.v1.Role
	7,  // 8: iam.audit.v1.IAMAuditEvent.timestamp:type_name -> google.protobuf.Timestamp
	1,  // 9: iam.audit.v1.IAMAuditEvent.subject:type_name -> iam.audit.v1.Actor
	2,  // 10: iam.audit.v1.IAMAuditEvent.services:type_name -> iam.audit.v1.Service
	1,  // 11: iam.audit.v1.IAMAuditEvent.admin:type_name -> iam.audit.v1.Actor
	5,  // 12: iam.audit.v1.IAMAuditEvent.result:type_name -> iam.audit.v1.Result
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_api_proto_iam_audit_v1_access_lifecycle_proto_init() }
func file_api_proto_iam_audit_v1_access_lifecycle_proto_init() {
	if File_api_proto_iam_audit_v1_access_lifecycle_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_iam_audit_v1_access_lifecycle_proto_rawDesc), len(file_api_proto_iam_audit_v1_access_lifecycle_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_iam_audit_v1_access_lifecycle_proto_goTypes,
		DependencyIndexes: file_api_proto_iam_audit_v1_access_lifecycle_proto_depIdxs,
		MessageInfos:      file_api_proto_iam_audit_v1_access_lifecycle_proto_msgTypes,
	}.Build()
	File_api_proto_iam_audit_v1_access_lifecycle_proto = out.File
	file_api_proto_iam_audit_v1_access_lifecycle_proto_goTypes = nil
	file_api_proto_iam_audit_v1_access_lifecycle_proto_depIdxs = nil
}
