// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.35.1
// source: api/proto/iam/audit/v1/envelope.proto

package auditv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Decision int32

const (
	Decision_DECISION_UNSPECIFIED Decision = 0
	Decision_DECISION_ALLOW       Decision = 1
	Decision_DECISION_DENY        Decision = 2
)

// Enum value maps for Decision.
var (
	Decision_name = map[int32]string{
		0: "DECISION_UNSPECIFIED",
		1: "DECISION_ALLOW",
		2: "DECISION_DENY",
	}
	Decision_value = map[string]int32{
		"DECISION_UNSPECIFIED": 0,
		"DECISION_ALLOW":       1,
		"DECISION_DENY":        2,
	}
)

func (x Decision) Enum() *Decision {
	p := new(Decision)
	*p = x
	return p
}

func (x Decision) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Decision) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_iam_audit_v1_envelope_proto_enumTypes[0].Descriptor()
}

func (Decision) Type() protoreflect.EnumType {
	return &file_api_proto_iam_audit_v1_envelope_proto_enumTypes[0]
}

func (x Decision) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Decision.Descriptor instead.
func (Decision) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_iam_audit_v1_envelope_proto_rawDescGZIP(), []int{0}
}

type AuditEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SchemaId      string                 `protobuf:"bytes,2,opt,name=schema_id,json=schemaId,proto3" json:"schema_id,omitempty"`
	SchemaVersion string                 `protobuf:"bytes,3,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	EventType     string                 `protobuf:"bytes,4,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Source        string                 `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	CorrelationId string                 `protobuf:"bytes,6,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	TraceId       string                 `protobuf:"bytes,7,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	TicketId      string                 `protobuf:"bytes,8,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	Actor         *Principal             `protobuf:"bytes,9,opt,name=actor,proto3" json:"actor,omitempty"`
	Subject       *Principal             `protobuf:"bytes,10,opt,name=subject,proto3" json:"subject,omitempty"`
	Resource      *Resource              `protobuf:"bytes,11,opt,name=resource,proto3" json:"resource,omitempty"`
	Action        string                 `protobuf:"bytes,12,opt,name=action,proto3" json:"action,omitempty"`
	Decision      Decision               `protobuf:"varint,13,opt,name=decision,proto3,enum=iam.audit.v1.Decision" json:"decision,omitempty"`
	Reason        string                 `protobuf:"bytes,14,opt,name=reason,proto3" json:"reason,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ReceivedAt    *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=received_at,json=receivedAt,proto3" json:"received_at,omitempty"`
	Extensions    map[string]string      `protobuf:"bytes,17,rep,name=extensions,proto3" json:"extensions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Fields        map[string]string      `protobuf:"bytes,18,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	PrevHash      string                 `protobuf:"bytes,19,opt,name=prev_hash,json=prevHash,proto3" json:"prev_hash,omitempty"`
	Hash          string                 `protobuf:"bytes,20,opt,name=hash,proto3" json:"hash,omitempty"`
	Payload       []byte                 `protobuf:"bytes,21,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditEnvelope) Reset() {
	*x = AuditEnvelope{}
	mi := &file_api_proto_iam_audit_v1_envelope_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditEnvelope) ProtoMessage() {}

func (x *AuditEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_iam_audit_v1_envelope_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditEnvelope.ProtoReflect.Descriptor instead.
func (*AuditEnvelope) Descriptor() ([]byte, []int) {
	return file_api_proto_iam_audit_v1_envelope_proto_rawDescGZIP(), []int{0}
}

func (x *AuditEnvelope) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AuditEnvelope) GetSchemaId() string {
	if x != nil {
		return x.SchemaId
	}
	return ""
}

func (x *AuditEnvelope) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *AuditEnvelope) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *AuditEnvelope) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *AuditEnvelope) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *AuditEnvelope) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *AuditEnvelope) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

func (x *AuditEnvelope) GetActor() *Principal {
	if x != nil {
		return x.Actor
	}
	return nil
}

func (x *AuditEnvelope) GetSubject() *Principal {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *AuditEnvelope) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *AuditEnvelope) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AuditEnvelope) GetDecision() Decision {
	if x != nil {
		return x.Decision
	}
	return Decision_DECISION_UNSPECIFIED
}

func (x *AuditEnvelope) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *AuditEnvelope) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *AuditEnvelope) GetReceivedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReceivedAt
	}
	return nil
}

func (x *AuditEnvelope) GetExtensions() map[string]string {
	if x != nil {
		return x.Extensions
	}
	return nil
}

func (x *AuditEnvelope) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *AuditEnvelope) GetPrevHash() string {
	if x != nil {
		return x.PrevHash
	}
	return ""
}

func (x *AuditEnvelope) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *AuditEnvelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type Principal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	DisplayName   string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Attributes    map[string]string      `protobuf:"bytes,4,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Principal) Reset() {
	*x = Principal{}
	mi := &file_api_proto_iam_audit_v1_envelope_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Principal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Principal) ProtoMessage() {}

func (x *Principal) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_iam_audit_v1_envelope_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Principal.ProtoReflect.Descriptor instead.
func (*Principal) Descriptor() ([]byte, []int) {
	return file_api_proto_iam_audit_v1_envelope_proto_rawDescGZIP(), []int{1}
}

func (x *Principal) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Principal) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Principal) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Principal) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type Resource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	System        string                 `protobuf:"bytes,1,opt,name=system,proto3" json:"system,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Environment   string                 `protobuf:"bytes,4,opt,name=environment,proto3" json:"environment,omitempty"`
	Criticality   string                 `protobuf:"bytes,5,opt,name=criticality,proto3" json:"criticality,omitempty"`
	Attributes    map[string]string      `protobuf:"bytes,6,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_api_proto_iam_audit_v1_envelope_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_iam_audit_v1_envelope_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_api_proto_iam_audit_v1_envelope_proto_rawDescGZIP(), []int{2}
}

func (x *Resource) GetSystem() string {
	if x != nil {
		return x.System
	}
	return ""
}

func (x *Resource) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Resource) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Resource) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *Resource) GetCriticality() string {
	if x != nil {
		return x.Criticality
	}
	return ""
}

func (x *Resource) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

var File_api_proto_iam_audit_v1_envelope_proto protoreflect.FileDescriptor

const file_api_proto_iam_audit_v1_envelope_proto_rawDesc = "" +
	"\n" +
	"%api/proto/iam/audit/v1/envelope.proto\x12\fiam.audit.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbd\a\n" +
	"\rAuditEnvelope\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tschema_id\x18\x02 \x01(\tR\bschemaId\x12%\n" +
	"\x0eschema_version\x18\x03 \x01(\tR\rschemaVersion\x12\x1d\n" +
	"\n" +
	"event_type\x18\x04 \x01(\tR\teventType\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\x12%\n" +
	"\x0ecorrelation_id\x18\x06 \x01(\tR\rcorrelationId\x12\x19\n" +
	"\btrace_id\x18\a \x01(\tR\atraceId\x12\x1b\n" +
	"\tticket_id\x18\b \x01(\tR\bticketId\x12-\n" +
	"\x05actor\x18\t \x01(\v2\x17.iam.audit.v1.PrincipalR\x05actor\x121\n" +
	"\asubject\x18\n" +
	" \x01(\v2\x17.iam.audit.v1.PrincipalR\asubject\x122\n" +
	"\bresource\x18\v \x01(\v2\x16.iam.audit.v1.ResourceR\bresource\x12\x16\n" +
	"\x06action\x18\f \x01(\tR\x06action\x122\n" +
	"\bdecision\x18\r \x01(\x0e2\x16.iam.audit.v1.DecisionR\bdecision\x12\x16\n" +
	"\x06reason\x18\x0e \x01(\tR\x06reason\x128\n" +
	"\ttimestamp\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12;\n" +
	"\vreceived_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"receivedAt\x12K\n" +
	"\n" +
	"extensions\x18\x11 \x03(\v2+.iam.audit.v1.AuditEnvelope.ExtensionsEntryR\n" +
	"extensions\x12?\n" +
	"\x06fields\x18\x12 \x03(\v2'.iam.audit.v1.AuditEnvelope.FieldsEntryR\x06fields\x12\x1b\n" +
	"\tprev_hash\x18\x13 \x01(\tR\bprevHash\x12\x12\n" +
	"\x04hash\x18\x14 \x01(\tR\x04hash\x12\x18\n" +
	"\apayload\x18\x15 \x01(\fR\apayload\x1a=\n" +
	"\x0fExtensionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xda\x01\n" +
	"\tPrincipal\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12G\n" +
	"\n" +
	"attributes\x18\x04 \x03(\v2'.iam.audit.v1.Principal.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x95\x02\n" +
	"\bResource\x12\x16\n" +
	"\x06system\x18\x01 \x01(\tR\x06system\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12 \n" +
	"\venvironment\x18\x04 \x01(\tR\venvironment\x12 \n" +
	"\vcriticality\x18\x05 \x01(\tR\vcriticality\x12F\n" +
	"\n" +
	"attributes\x18\x06 \x03(\v2&.iam.audit.v1.Resource.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*K\n" +
	"\bDecision\x12\x18\n" +
	"\x14DECISION_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eDECISION_ALLOW\x10\x01\x12\x11\n" +
	"\rDECISION_DENY\x10\x02B*Z(iam-audit/api/proto/iam/audit/v1;auditv1b\x06proto3"

var (
	file_api_proto_iam_audit_v1_envelope_proto_rawDescOnce sync.Once
	file_api_proto_iam_audit_v1_envelope_proto_rawDescData []byte
)

func file_api_proto_iam_audit_v1_envelope_proto_rawDescGZIP() []byte {
	file_api_proto_iam_audit_v1_envelope_proto_rawDescOnce.Do(func() {
		file_api_proto_iam_audit_v1_envelope_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_iam_audit_v1_envelope_proto_rawDesc), len(file_api_proto_iam_audit_v1_envelope_proto_rawDesc)))
	})
	return file_api_proto_iam_audit_v1_envelope_proto_rawDescData
}

var file_api_proto_iam_audit_v1_envelope_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_iam_audit_v1_envelope_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_proto_iam_audit_v1_envelope_proto_goTypes = []any{
	(Decision)(0),                 // 0: iam.audit.v1.Decision
	(*AuditEnvelope)(nil),         // 1: iam.audit.v1.AuditEnvelope
	(*Principal)(nil),             // 2: iam.audit.v1.Principal
	(*Resource)(nil),              // 3: iam.audit.v1.Resource
	nil,                           // 4: iam.audit.v1.AuditEnvelope.ExtensionsEntry
	nil,                           // 5: iam.audit.v1.AuditEnvelope.FieldsEntry
	nil,                           // 6: iam.audit.v1.Principal.AttributesEntry
	nil,                           // 7: iam.audit.v1.Resource.AttributesEntry
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_api_proto_iam_audit_v1_envelope_proto_depIdxs = []int32{
	2,  // 0: iam.audit.v1.AuditEnvelope.actor:type_name -> iam.audit.v1.Principal
	2,  // 1: iam.audit.v1.AuditEnvelope.subject:type_name -> iam.audit.v1.Principal
	3,  // 2: iam.audit.v1.AuditEnvelope.resource:type_name -> iam.audit.v1.Resource
	0,  // 3: iam.audit.v1.AuditEnvelope.decision:type_name -> iam.audit.v1.Decision
	8,  // 4: iam.audit.v1.AuditEnvelope.timestamp:type_name -> google.protobuf.Timestamp
	8,  // 5: iam.audit.v1.AuditEnvelope.received_at:type_name -> google.protobuf.Timestamp
	4,  // 6: iam.audit.v1.AuditEnvelope.extensions:type_name -> iam.audit.v1.AuditEnvelope.ExtensionsEntry
	5,  // 7: iam.audit.v1.AuditEnvelope.fields:type_name -> iam.audit.v1.AuditEnvelope.FieldsEntry
	6,  // 8: iam.audit.v1.Principal.attributes:type_name -> iam.audit.v1.Principal.AttributesEntry
	7,  // 9: iam.audit.v1.Resource.attributes:type_name -> iam.audit.v1.Resource.AttributesEntry
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_api_proto_iam_audit_v1_envelope_proto_init() }
func file_api_proto_iam_audit_v1_envelope_proto_init() {
	if File_api_proto_iam_audit_v1_envelope_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_iam_audit_v1_envelope_proto_rawDesc), len(file_api_proto_iam_audit_v1_envelope_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_iam_audit_v1_envelope_proto_goTypes,
		DependencyIndexes: file_api_proto_iam_audit_v1_envelope_proto_depIdxs,
		EnumInfos:         file_api_proto_iam_audit_v1_envelope_proto_enumTypes,
		MessageInfos:      file_api_proto_iam_audit_v1_envelope_proto_msgTypes,
	}.Build()
	File_api_proto_iam_audit_v1_envelope_proto = out.File
	file_api_proto_iam_audit_v1_envelope_proto_goTypes = nil
	file_api_proto_iam_audit_v1_envelope_proto_depIdxs = nil
}
